/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.easyea.edao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * 定义一个数据库操作的Statements的会话
 * @author louis
 */
public interface StatementSession {
    /**
     * 是否支持批量处理
     * @return 
     */
    public boolean enableBatch();
    
    public void setConnection(Connection con);
    
    public Connection getConnection();
    
    public boolean getAutoCommit() throws SQLException;
    
    public void setAutoCommit(boolean autoCommit) throws SQLException;
    
    public void commit() throws SQLException;
    
    /**
     * 获取一个Statement
     * @return 
     * @throws java.sql.SQLException 
     */
    public Statement statement() throws SQLException;
    /**
     * 根据sql语句获取一个PreparedStatement
     * @param sql
     * @return 
     * @throws java.sql.SQLException 
     */
    public PreparedStatement prepareStatement(String sql) throws SQLException;
    
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys)
            throws SQLException;
    
    /**
     * 关闭本次打开的所有的Statements
     */
    public void closeStatements();
    
    public void closeConnection();
}
