/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.easyea.edao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * 定义一个数据库操作的Statements的会话
 * @author louis
 */
public interface StatementSession extends AutoCloseable {
    /**
     * 是否支持统计执行sql的数量
     * @return 
     */
    public boolean enableStat();
    
    public void setEnableStat(boolean enable);
    
    public void addSelect(int count);
    
    public void addInsert(int count);
    
    public void addUpdate(int count);
    
    public void clearSqlStat();
    
    public SqlStat getSqlStat();
    
    /**
     * 是否支持批量处理
     * @return 
     */
    public boolean enableBatch();
    /**
     * 设置该Session的数据库连接
     * @param con 数据库连接对象
     */
    public void setConnection(Connection con);
    /**
     * 获取该StatementSession的数据库连接
     * @return 返回数据库的连接
     */
    public Connection getConnection();
    /**
     * 获取该StatementSession是否自动提交的状态
     * @return 是否自动提交的状态
     * @throws SQLException 
     */
    public boolean getAutoCommit() throws SQLException;
    /**
     * 设置是否支持数据库的自动提交
     * @param autoCommit 是否自动提交
     * @throws SQLException 
     */
    public void setAutoCommit(boolean autoCommit) throws SQLException;
    /**
     * commit需要提交的数据
     * @throws SQLException 
     */
    public void commit() throws SQLException;
    
    /**
     * 获取一个Statement
     * @return 
     * @throws java.sql.SQLException 
     */
    public Statement statement() throws SQLException;
    /**
     * 根据sql语句获取一个PreparedStatement
     * @param sql
     * @return 
     * @throws java.sql.SQLException 
     */
    public PreparedStatement prepareStatement(String sql) throws SQLException;
    
    /**
     * 根据sql语句获取一个PreparedStatement的对象
     * @param sql 需要执行的sql
     * @param autoGeneratedKeys 是否自增字段
     * @return 返回PreparedStatment对象
     * @throws SQLException 
     */
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys)
            throws SQLException;
    
    /**
     * 关闭本次打开的所有的Statements
     */
    public void closeStatements();
    /**
     * 关闭本次打开的所有的数据库连接
     */
    public void closeConnection();
}
